name: safe_roads
description: "Safe Roads is a CCTV camera monitoring system to keep an eye on accidents in real time."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  fluttertoast: ^8.2.4
  file_saver: ^0.2.9
  path_provider: ^2.1.2
  flutter_file_dialog: ^3.0.2
  http:
  flutter:
    sdk: flutter


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  image_path: "assets/icons/icon.jpeg"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  adaptive_icon_background: "#dc1a22"
  web:
    generate: true
    image_path: "assets/icons/icon.jpeg"
    background_color: "#dc1a22"


flutter:
  uses-material-design: true
  assets:
    - assets/images/background_auth.png
    - assets/images/background_home.jpg

  fonts:
    - family: JejuHallasan
      fonts:
        - asset: fonts/JejuHallasan-Regular.ttf
    
    - family: Khand
      fonts:
        - asset: fonts/Khand-Regular.ttf

    - family: Kreon
      fonts:
        - asset: fonts/Kreon-Regular.ttf
    
    - family: SourceSans3
      fonts:
        - asset: fonts/SourceSans3-Regular.ttf
    
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
