name: safe_roads
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  fluttertoast: ^8.2.4
  flutter:
    sdk: flutter


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  change_app_package_name: ^1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/background_auth.jpg
    - assets/images/background_home.jpg

  fonts:
    - family: JejuHallasan
      fonts:
        - asset: fonts/JejuHallasan-Regular.ttf
    
    - family: Khand
      fonts:
        - asset: fonts/Khand-Regular.ttf

    - family: Kreon
      fonts:
        - asset: fonts/Kreon-Regular.ttf
    
    - family: SourceSans3
      fonts:
        - asset: fonts/SourceSans3-Regular.ttf
    
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
