// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMhQU2kiJZGSr7zj9XOG4NlJaCgHQrjyQ',
    appId: '1:56363785121:web:3f4e6fdcb5928243b149e0',
    messagingSenderId: '56363785121',
    projectId: 'saferoads-2026',
    authDomain: 'saferoads-2026.firebaseapp.com',
    storageBucket: 'saferoads-2026.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCr_Wj8eZvg_IPfIEKNFyDAZ4r9-5hYTE',
    appId: '1:56363785121:android:68e81384cb8399f7b149e0',
    messagingSenderId: '56363785121',
    projectId: 'saferoads-2026',
    storageBucket: 'saferoads-2026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi0498K9PYqbL0QoNIZtFO4T1G6sGSOHI',
    appId: '1:56363785121:ios:1bf55b921e973640b149e0',
    messagingSenderId: '56363785121',
    projectId: 'saferoads-2026',
    storageBucket: 'saferoads-2026.appspot.com',
    iosBundleId: 'com.example.safeRoads',
  );
}
